# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'reportlab.lib.pagesizes',
        'reportlab.lib.units',
        'reportlab.pdfgen.canvas',
        'reportlab.pdfbase.pdfdoc',
        'reportlab.pdfbase.ttfonts',
        'reportlab.rl_config'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes = [
    # ReportLab extras you don't need
    'reportlab.graphics',
    'reportlab.graphics.barcode',
    'reportlab.graphics.charts',
    'reportlab.graphics.renderPDF',
    'reportlab.graphics.renderPS',
    'reportlab.graphics.renderSVG',
    'reportlab.graphics.widgetbase',
    'reportlab.graphics.widgets',
    'reportlab.platypus',
    'reportlab.lib.styles',
    'reportlab_settings',
    'requests',
    'uharfbuzz',
    'defusedxml',
    'bz2',
    'lzma',
    'multiprocessing',
    'sqlite3',
    'asyncio',
    'pwd',
    'grp',
    'fcntl',
    'posix',
    '_hashlib',
    '_ssl',
    '_ctypes',
    'dis',
    'opcode',
    'inspect',
    'unittest',
    'pdb',
    'doctest',
    'cProfile',
    'trace',
    'timeit'
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ShareMyCar',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=a.excludes,
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['static\\red_car_icon.ico'],
)
